language: go

go:
  - "1.12"
  - "1.13"
  - master

# Allow builds from tip to fail - they might be in an unstable state
jobs:
  allow_failures:
    - go: master

env:
  - GO111MODULE=on

before_install:
  - go get github.com/wadey/gocovmerge
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

script:
  - go test -v ./...
  - go vet ./...

after_success:
  - ./.generate_coverage.sh
  - goveralls -coverprofile=full_cov.out -service=travis-ci